sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build source branch only

before_install:
  - export TZ='Asia/Shanghai'

script:
  - hexo generate # generate static files

after_script:
  - cd ./public
  - pwd
  - git status
  - git remote -v
  - git init
  - git config user.name "chen"
  - git config user.email "gakiclin@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master